- id: oca-check-readme
  name: Check odoo module Readme
  description: Check if the Odoo module has readme
  entry: oca-check-readme
  args: []
  language: python
  types: [file]
  files: __manifest__.py
