- id: odoo-missing-readme
  name: Odoo module check readme file exists
  entry: odoo-missing-readme
  args: []
  name: odoo-missing-readme
  language: python
  types: [file]
  language: python
  files: \_\_manifest\_\_.py$
- id: odoo-rst-syntax
  entry: odoo-rst-syntax
  args: []
  name: RST Syntax
  language: python
  types: [file]
  language: python
  files: \.rst$
